---

- include: mumble.yml

- include: mumble-web.yml
  when: mumble_web
  tags: mumble-web

- include: mumble-ldapauth.yml
  when: murmur_ldapauth
  tags: mumble-ldap

- include: monitoring.yml
  when: murmur_monitoring_monit_enabled or murmur_monitoring_munin_enabled
